import "./globals.css";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Shared/Footer/Footer";
import AuthProvider from "@/services/AuthProvider";

export const metadata = {
  title: "Car Doctor Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="carDoctorTheme">
      <body>
        <div className="max-w-7xl mx-auto">
          <AuthProvider>
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
